# Dockerfile (example targeting 1.18)
FROM flink:1.17
COPY src/main/resources/generated_sales_data.csv /tmp/generated_sales_data.csv
COPY target/flink-playground-0.1.jar /opt/flink/examples/SalesAnalysis.jar